FROM mcr.microsoft.com/playwright/java:v1.58.0-noble

ENV STRUCTURIZR_PLAYWRIGHT=true

COPY structurizr-application/target/structurizr-*.war /usr/local/structurizr.war
COPY structurizr-themes /usr/local/structurizr-themes
COPY entrypoint.sh /usr/local/entrypoint.sh

WORKDIR /usr/local/structurizr

ENTRYPOINT ["/usr/local/entrypoint.sh"]